---
driver:
  name: docker
  privileged: true
  use_sudo: false 

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.3
  - name: centos-6.8

suites:
  - name: dev
    driver:
      run_command: /usr/sbin/init
    run_list:
      - recipe[lcd_web::default]
    attributes: { 'java': { 'jdk_version': '7' } }
    driver_config:
      forward:
        - 8080:80
    excludes: centos-6.8
  - name: prod
    driver:
      run_command: /sbin/init
    run_list:
      - recipe[lcd_web::default]
    attributes: { 'java': { 'jdk_version': '6' } }
    driver_config:
      forward:
        - 8081:80
    includes: centos-6.8